version: "3.4"

services:
  go-indexer:
    image: pierreribault/go-indexer:latest
    build:
      context: .
      target: setup
    environment:
      DOWNLOAD_FOLDER_NAME: "downloads"
    volumes:
      - "./storage/downloads:/app/storage/downloads"
      - "./storage/medias:/app/storage/medias"